spring.application.name=springdemo
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/fifapp
spring.datasource.username=fifapp_admin
spring.datasource.password=fifapp_admin
spring.datasource.driver-class-name=org.postgresql.Driver


spring.flyway.enabled=true
spring.flyway.schemas=flyway_training
spring.flyway.default-schema=flyway_training
spring.flyway.create-schemas=true

logging.level.org.flywaydb=DEBUG