spring.application.name=springdemo
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/fifapp
spring.datasource.username=fifapp_admin
spring.datasource.password=fifapp_admin
spring.datasource.driver-class-name=org.postgresql.Driver